version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: nestDB

  nestapp-dev:
    depends_on:
      - postgres
    build: 
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: nest-graphql-dev
    container_name: NestApp-dev
    restart: always
    ports:
      - "3000:3000"

volumes:
  db_data: