version: '3'

services: 
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: nestDB

  # neon-proxy:
  #   build:
  #     context: ./docker/neon-proxy/
  #     dockerfile: Dockerfile
  #   environment:
  #     - PG_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  #   ports:
  #     - '4444:4444'
  #   depends_on:
  #     - postgres

  nestapp:
    depends_on:
      - postgres
    build: 
      context: .
      dockerfile: ./docker/build/Dockerfile
    image: nest-graphql
    container_name: NestApp
    restart: always
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - postgres
      