version: '3'

services: 
  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: anylistDB
    volumes:
      - ./postgres:/var/lib/postgresql/data

  nestTemplate:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: nest-graphql
    container_name: NestTemplate
    restart: always
    ports:
      - "3000:3000"

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      CSRF_SECRET: ${CSRF_SECRET}
      COOKIE_KEY: ${COOKIE_KEY}
      LOCAL_PROVIDER: ${LOCAL_PROVIDER}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}